### PR TITLE
Undeprecate draw aaline blend

### LINKED ISSUE #2739: Restore pygame.draw.aaline ` blend` argument
I got a report from Irv Kalb on discord that the removal of the `blend` argument in aaline in https://github.com/pygame-community/pygame-ce/pull/2506 broke some of their code. 

I'm following up with them on how they didn't see (or did they just ignore?) the years of deprecation warnings.

Regardless, they suggested rather than removing the parameter entirely (resulting in crashes), it could just be ignored. I think this is a good idea. It could be ignored and raise a deprecation warning complaining about its use. If we want to remove it entirely, why not do that in a potential future pygame-ce 3?

ALSO, Irv pointed that the draw example at the bottom of the draw docs page still uses the argument. So that needs to be fixed.

### PR DESCRIPTION
**Pull request by oddbookworm**
fixes #2739 and properly deprecates the blend argument so that if it's used, a warning will always be emitted instead of just false

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
Perhaps the formatting changes that are unrelated to this PR should be a separate PR? It's probably the new version of clang-format messing things up. It has been causing my PRs to fail too

**Comment by oddbookworm** [comment]
> Perhaps the formatting changes that are unrelated to this PR should be a separate PR? It's probably the new version of clang-format messing things up. It has been causing my PRs to fail too

I opened #2744 to apply the formatting changes. I can rebase this pull when that merges

**Comment by Starbuck5** [comment]
I think it’s fine to leave the feature removed (commits don’t need to be reverted). It’s just that the parameter should be un-removed and should always raise a depreciation warning.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada:

File: src_c/draw.c [hunk 1]
```diff
@@ -105,18 +105,29 @@ aaline(PyObject *self, PyObject *arg, PyObject *kwargs)
     PyObject *colorobj, *start, *end;
     SDL_Surface *surf = NULL;
     float startx, starty, endx, endy;
+    PyObject *blend;
```
Comment (Starbuck5) [inline src_c/draw.c:108]: Shouldn't this start as null?

Comment (oddbookworm) [reply src_c/draw.c:108]: oops

**Review by Starbuck5 — APPROVED** [review]
Alrighty, thanks! Code looks good, haven't tested locally.
