### PR TITLE
Fix break when the OS resizes our window in `set_mode`

### LINKED ISSUE #2991: Linux is broke, no idea cause
[Too long to explain in the time I have, so here's a discord link](https://discord.com/channels/772505616680878080/772847140992712734/1262100174680100895)

[SDL issue I opened to see if they know what's going on](https://github.com/libsdl-org/SDL/issues/10270)

Fix I found is to put an internal flip after we pump events in `set_mode` to force an update
image

This updates the screen to be whatever minimum size is being pushed on us, but now tests are failing because we can't guarantee that a small screen size is honored

### PR DESCRIPTION
**Pull request by oddbookworm**
Hopefully fixes #2991. I suspect that there's a lot I missed, so @robertpfeiffer @ankith26 @Starbuck5 please take a long look at these changes.

I haven't found a reliable way we can predict what the size the OS will force small windows to is, so I resorted to seeing what SDL says it is. Maybe I could just manually go through the event queue instead of pumping and grabbing the size from there?

### CODE REVIEW

File: src_c/display.c [hunk 1]
```diff
@@ -1340,8 +1345,38 @@ pg_set_mode(PyObject *self, PyObject *arg, PyObject *kwds)
...
 
-    /*probably won't do much, but can't hurt, and might help*/
+    /*
+     * Can potentially yield a window resize event that forcibly changes
+     * the window size. This would invalidate the current surface we store,
+     * which can cause us to segfault in the event that we reference that
+     * surface later. So we need to flip, which forces us to update that
+     * surface as needed.
+     */
     SDL_PumpEvents();
```
Comment (ankith26) [inline src_c/display.c:1355]: This call was rather arbitrary anyways, removing it probably fixes the issue instead of needing the special-cased flip internal call?

By fixes the issue, I mean defers the handling to the next point of time that pump events is called.

Comment (ankith26) [reply src_c/display.c:1355]: though it's just a comment, your approach is probably better as it raises a warning and lets the user know right at the function call.

File: src_c/display.c [hunk 2]
```diff
@@ -1340,8 +1345,38 @@ pg_set_mode(PyObject *self, PyObject *arg, PyObject *kwds)
...
+    pg_flip_internal(state);
```
Comment (ankith26) [inline src_c/display.c:1356]: This is the second `pg_flip_internal` call in this function. The first one is called just after setting the screen to black. I reckon, that part must be removed and handled here instead

File: src_c/display.c (hunk 1 above)
Comment (oddbookworm) [reply src_c/display.c:1355]: Yeah, I'd rather the user know immediately, rather than some nebulous point in the future when the event queue is finally pumped

File: src_c/display.c (hunk 2 above)
Comment (oddbookworm) [reply src_c/display.c:1355]: removed the other one

File: src_c/display.c [hunk 3]
```diff
@@ -1340,8 +1344,38 @@ pg_set_mode(PyObject *self, PyObject *arg, PyObject *kwds)
...
+     * such a way that it can, at least our internal stuff, can
+     * be respected enough that we don't need to issue a warning
+     */
+    if (!state->using_gl && ((flags & (PGS_SCALED | PGS_FULLSCREEN)) == 0) &&
+        !vsync) {
+        SDL_Surface *sdlSurf = SDL_GetWindowSurface(win);
+        if (((sdlSurf->w != w_actual) || (sdlSurf->h != h_actual)) &&
+            ((sdlSurf->flags & SDL_WINDOW_FULLSCREEN_DESKTOP) != 0)) {
+            char buffer[150];
+            char *formatString =
```
Comment (ankith26) [inline src_c/display.c:1369]: Just a minor nitpick, could you make use of snake case naming instead here?

File: src_c/display.c [hunk 4]
```diff
@@ -1340,8 +1344,38 @@ pg_set_mode(PyObject *self, PyObject *arg, PyObject *kwds)
...
+
+    /*
+     * Tell user if their requested screen size is ignored
+     * OpenGL, SCALED, and FULLSCREEN mess with the screensize in
+     * such a way that it can, at least our internal stuff, can
+     * be respected enough that we don't need to issue a warning
+     */
+    if (!state->using_gl && ((flags & (PGS_SCALED | PGS_FULLSCREEN)) == 0) &&
+        !vsync) {
+        SDL_Surface *sdlSurf = SDL_GetWindowSurface(win);
```
Comment (ankith26) [inline src_c/display.c:1365]: Now that the flip is called, we probably don't need this extra call. We just need to use `surface->surf` instead

File: src_c/display.c (hunk 3 above)
Comment (oddbookworm) [reply src_c/display.c]: done

File: src_c/display.c (hunk 4 above)
Comment (oddbookworm) [reply src_c/display.c]: done

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada:

**Review by MyreMylar — APPROVED** [review]
OK, LGTM 👍
