### PR TITLE
Run display autoinit on window API, fixes

### LINKED ISSUE #2605: Maximizing a window invalidates the window surface
OS: Windows 10, Python: 3.9

```py
import pygame
from pygame._sdl2 import Window

window = Window(resizable=True)
screen = window.get_surface()

clock = pygame.Clock()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit
        
        if event.type == pygame.KEYDOWN and event.key == pygame.K_1:
            window.maximize()
        
    screen.fill("white")
    window.flip()
```

When I press 1, get `pygame.error: Window surface is invalid, please call SDL_GetWindowSurface() to get a new surface`

### PR DESCRIPTION
**Pull request by ankith26**
fixes #2605

This PR takes the `display.set_mode`-like approach and implicitly calls display init whenever a window is constructed.

### CODE REVIEW

File: src_c/window.c [hunk 1]
```diff
@@ -7,6 +7,8 @@
 #include "doc/sdl2_video_doc.h"
 #include "doc/window_doc.h"
 
+int is_window_mod_init = 0;
```
Comment (oddbookworm) [inline src_c/window.c:10]: Should this be static?

Comment (ankith26) [reply src_c/window.c:10]: It doesn't really make much of a difference in a context like this, but sure, I can make the change

**Review by MyreMylar — APPROVED** [review]
OK, LGTM 👍

**Review by oddbookworm — APPROVED** [review]
LGTM

**Comment by robertpfeiffer** [comment]
is this really how we want to to things? I added this behaviour to pygame.display as a hack to keep backward compat with pygame 1.9, which required a call to set_mode after a VIDEORESIZE event.

**Comment by ankith26** [comment]
I would not have minded the raise warning/error approach, but then I also don't see a problem with the currently implemented approach
