### PR TITLE
Raise an error when source and destination surfaces are the same (in `box_blur` and `gaussian_blur`).

### LINKED ISSUE #2102: `transform.box_blur` works incorrectly.
**Test Code**
```python
import pygame
import sys

sf=pygame.image.load("peppers3.tif")
pygame.display.init()
dsf=pygame.display.set_mode((1280,720))

while 1:
    dsf.fill((0,150,0))

    dsf.blit(sf, (640,0,0,0))

    pygame.transform.box_blur(dsf,10,dest_surface=dsf)

    dsf.blit(sf,(0,0,1,1))
    pygame.display.update()
    for event in pygame.event.get():
        if event.type==pygame.QUIT:
            sys.exit()

```
image

### PR DESCRIPTION
**Pull request by yunline**
Continue from #2103
Fix #2102

### CODE REVIEW

**Review by Matiiss — CHANGES_REQUESTED** [review]
This should probably have a note in the docs that passing the calling surface as destination surface would raise an exception. Otherwise looks good to me.

**Review by Matiiss — APPROVED** [review]
LGTM 👍

File: src_c/transform.c [hunk 1]
```diff
@@ -3144,6 +3144,11 @@ blur(pgSurfaceObject *srcobj, pgSurfaceObject *dstobj, int radius,
         retsurf = pgSurface_AsSurface(dstobj);
     }
 
+    if (retsurf->pixels == src->pixels) {
```
Comment (Starbuck5) [inline src_c/transform.c:3147]: Is this a viable way of testing that surfaces have the same data?

Like I believe subsurfaces might have a `->pixels` pointer within the existing surface data region.

Could it test if the pixels regions overlap? Like something around `if (retsurf->pixels <= src->pixels && src->pixels <= retsurf->pixels + retsurf->pitch * retsurf->h) {}`

I'm not telling you to do this, this is a genuine question.

Comment (Matiiss) [reply src_c/transform.c:3147]: My understanding is that since pixel addresses are compared no two different surfaces would have the same pixel address, right? So, only the same surface would succeed that check. As for subsurfaces, they also pass that check and an exception is raised. Which makes sense as that's still the same surface under the hood.

Comment (Starbuck5) [reply src_c/transform.c:3147]: As I suspected, subsurfaces do have different addresses:

```py
>>> import pygame
pygame-ce 2.3.0.dev3 (SDL 2.26.4, Python 3.9.5)
>>> a = pygame.Surface((500,50))
>>> b = a.subsurface((10,10,100,30))
>>> b
<Surface(100x30x32)>
>>> a
<Surface(500x50x32)>
>>> a._pixels_address
1743672180768
>>> b._pixels_address
1743672200808
>>>
```

Comment (yunline) [reply src_c/transform.c:3147]: > As I suspected, subsurfaces do have different addresses:

Yes, but they are in different size, which will be caught by here:
https://github.com/pygame-community/pygame-ce/blob/2a21a5db2ba5b4180f948fd952b8423221e6a552/src_c/transform.c#L3152-L3155

File: src_c/transform.c [hunk 2]
```diff
@@ -3144,6 +3144,16 @@ blur(pgSurfaceObject *srcobj, pgSurfaceObject *dstobj, int radius,
...
     }
 
+    Uint8 *ret_start = retsurf->pixels;
+    Uint8 *ret_end = ret_start + retsurf->h * retsurf->pitch;
+    Uint8 *src_start = src->pixels;
+    Uint8 *src_end = src_start + src->h * src->pitch;
+    if ((ret_start <= src_start && ret_end >= src_start) ||
+        (src_start <= ret_start && src_end >= ret_start)) {
+        return RAISE(PyExc_ValueError,
+                     "Source and destination surfaces are overlapping.");
```
Comment (Starbuck5) [inline src_c/transform.c:3154]: The fact that they're overlapping is not a good error message, imo.

"Blur routines do not support dest_surfaces that share pixels with the source surface. Likely the surfaces are the same, one of them is a subsurface, or they are sharing the same buffer."

^ Something like this?

I tried to put it in words that would make sense with the context of the pygame API.

**Review by Starbuck5 — APPROVED** [review]
Left some error message feedback to resolve before merge, otherwise looks good.
