### PR TITLE
Make window subclassable

### LINKED ISSUE #2625: Window should be subclassable
Currently it is not, and it is marked as such with types, which is good.

```
>>> class ManagedWindow(pygame.Window):
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type 'pygame.window.Window' is not an acceptable base type
```

It's hard to sell this as an OOP interface into windowing functions when it can't be used to define your own objects :)

### PR DESCRIPTION
**Pull request by zoldalma999**
Fixes #2625

### CODE REVIEW

File: src_c/window.c [hunk 1]
```diff
@@ -96,8 +96,7 @@ pg_display_resource(char *filename)
 
 static PyTypeObject pgWindow_Type;
 
-#define pgWindow_Check(x) \
-    (PyObject_IsInstance((x), (PyObject *)&pgWindow_Type))
+#define pgWindow_Check(x) (PyType_IsSubtype(Py_TYPE(x), &pgWindow_Type))
```
Comment (ankith26) [inline src_c/window.c:99]: Does this line need changing?

According to the [`PyObject_IsInstance`](https://docs.python.org/3/c-api/object.html#c.PyObject_IsInstance) docs:
> Return 1 if inst is an instance of the class cls or a subclass of cls, or 0 if not. On error, returns -1 and sets an exception.

Comment (zoldalma999) [reply src_c/window.c]: You are right, that should work. Changed it back

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada:
