### PR TITLE
Fix scaled-after-non-scaled usage

### LINKED ISSUE #2376: Mac - After creating a window using `display.set_mode()`, cannot use `display.set_mode()` again to change to SCALED
**Environment:**
- Operating system:  macOS Monterey 12.6.8
- Hardware:  MacBook Pro (early 2015)
- Processer:  2.7GHz Dual Core Intel Core i5
- Python version:  3.11.4
- SDL version:  SDL 2.26.5
- pygame-ce version:  2.3.1.dev4 (also reproduced on 2.3.0 and 2.3.1.dev2)

**Bug behaviour:**
When initializing a window using `display.set_mode()` and NOT using the SCALED flag, if you later attempt to use `display.set_mode()` again to change the window to be SCALED it fails with a pygame error.

**Expected behavior:**
Calling `display.set_mode()` again using SCALED should result in the window being resized with appropriate scale. 

**Screenshots**
image

**Steps to reproduce:**
1. create a window that is not SCALED using the standard set_mode method (i.e. `pygame.display.set_mode((width, height))`)
2. use set_mode again to change the display to be SCALED (i.e. `pygame.display.set_mode((width, height), pygame.SCALED)`)

**Test code:**
Pressing the 1 key re-sets the window, pressing 2 key crashes the program instead of producing a SCALED window.

```
import pygame

pygame.init()

screen = pygame.display.set_mode((800, 600))

run = True
while run:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            run = False
            break
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_1:
                screen = pygame.display.set_mode((800, 600))
            elif event.key == pygame.K_2:
                screen = pygame.display.set_mode((800, 600), pygame.SCALED)
    screen.fill("blue")
    pygame.display.flip()

pygame.quit()
```

**Error details:**
pygame.error: failed to create renderer

**Notes:**
I have tested the code on my Windows 11 machine and it works fine with the same Python and pygame-ce version.
Also, if the window is created with the SCALED flag, using `display.set_mode()` again without the SCALED flag correctly resizes to the window size specified. However, the same issue occurs after this, where an error is seen if you try to change back to SCALED again.

### LINKED ISSUE #2737: Calling `pygame.display.set_mode` a second time crashes with `SCALED` flag if it hasn't been called with it the first time.
**Environment:**

- **Operating system**: Windows 10
- **Python version**: 3.11.4
- **SDL version**: 2.28.5
- **pygame-ce version**: 2.4.1

**Current behavior:**

When the method `pygame.display.set_mode` is called a second time with `SCALED` flag and hasn't been called the first time with `SCALED` flag, pygame crash with the following error:

```
pygame.error: failed to create renderer
```

The error happens only when `set_mode` is called with `SCALED` flag and if it hasn't been set with it before.

**Expected behavior:**

This seems to happen only since 2.4.0, I tested it with 2.3.2 and it works properly.

**Steps to reproduce:**

1. Call `set_mode` without `SCALED` flag.
2. Call `set_mode` a second time with `SCALED` flag makes pygame crash.

Or:

1. Call `set_mode` with `SCALED` flag.
2. Call `set_mode` a second time without it, this will work as intended.
3. Call `set_mode` a third time with `SCALED` flag, then it crashes.

**Test code**

Just press SPACE key to switch mode.

```python
import pygame

pygame.init()

screen = pygame.display.set_mode((500, 500), pygame.RESIZABLE)

running = True
fullscreen = False

while running:
    for event in pygame.event.get():
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_SPACE:
                fullscreen = not fullscreen
                if fullscreen is True:
                    screen = pygame.display.set_mode((500, 500), pygame.FULLSCREEN | pygame.SCALED)
                else:
                    screen = pygame.display.set_mode((500, 500), pygame.RESIZABLE)

        if event.type == pygame.QUIT:
            running = False

    screen.fill((255, 255, 255))
    pygame.draw.circle(screen, (0, 255, 0), (250, 250), 75)
    pygame.display.flip()

pygame.quit()
```

### PR DESCRIPTION
**Pull request by ankith26**
this PR fixes #2737 and fixes #2376 (they are essentially the same issue).

Note that I couldn't reproduce the original issue on Ubuntu, however @zoldalma999 has tested this branch and reported that this fix has worked on windows. Would be nice if someone gave this a test on a mac as well.

Also worth mentioning that the fix only works for SDL 2.28.0+, but all the wheels we distribute are on 2.30.3 so this shouldn't be a big deal.

It was also mentioned in one of the linked issues that #2571 is also the same issue, but I don't think that's the case.

### CODE REVIEW

File: src_c/display.c [hunk 1]
```diff
@@ -1238,6 +1238,17 @@ pg_set_mode(PyObject *self, PyObject *arg, PyObject *kwds)
                     SDL_SetHintWithPriority(SDL_HINT_RENDER_SCALE_QUALITY,
                                             "nearest", SDL_HINT_DEFAULT);
 
+#if SDL_VERSION_ATLEAST(2, 28, 0)
+                    /* If the window has a surface associated with it already,
+                     * we need to destroy it (if possible) because now we are
+                     * associating a renderer with it.
+                     * I don't know how to achieve the same effect on older
+                     * SDL versions that don't support below functions */
```
Comment (zoldalma999) [inline src_c/display.c:1246]: I don't think we need to do this stuff for versions below 2.28 (which added these functions) as they did not error out if they already had a surface.

**Review by zoldalma999 — APPROVED** [review]
As Anktith said, this works for me with SDL 2.30.2, with the original reproducer.

File: src_c/display.c (hunk 1 above)
Comment (ankith26) [reply src_c/display.c]: In my latest code I have vendored in the destroy window logic from SDL code, now we are covered for all versions

**Comment by ankith26** [comment]
A bit of interesting history: these new API functions were basically added for us by the SDL folks in response to issue #2190 so we have to make use of it!

File: src_c/display.c [hunk 2]
```diff
@@ -824,6 +824,64 @@ _get_display(SDL_Window *win)
...
+PG_DestroyWindowSurface(SDL_Window *win)
+{
+    if (SDL_HasWindowSurface(win)) {
+        SDL_DestroyWindowSurface(win);
+    }
+}
+#else
+/* SDL_Window struct, as taken from the SDL source (except some pointer types
+ * have been replaced with `void *`) */
+struct SDL_Window {
```
Comment (Starbuck5) [inline src_c/display.c:838]: This is crazyyyyy, I appreciate the effort you put in Ankith!

I mean we've done stuff like it before but still

Comment (ankith26) [reply src_c/display.c:838]: thanks, it wasn't much effort, but yeah, I am fairly confident this approach is robust and can cover all our supported versions

Comment (ankith26) [reply src_c/display.c]: I actually had to revert this solution because it was leading to segfaults on 32-bit ARM, and I had no idea how those could be resolved.

**Comment by rethanon** [comment]
This does seem to fix #2737 but doesn't appear to fix #2376. I tested it today and the error still happens on my Mac (but is fixed on my Windows 11 machine)

**Comment by ankith26** [comment]
It doesn't fix #2376 as of now, but SDL has patched the underlying issue and the fix should be available in the SDL bump, so let this PR wait for that

**Comment by ankith26** [comment]
After the latest rebase, this PR should fix the issue on mac as well.

**Comment by rethanon** [comment]
Tested on my Mac (reminder it's a 2015 Intel based MacBook Pro) and yes indeed the tests were successful with the latest PR, thanks!
